// spring2024/week9/svelte-client/src/lib/Counter.svelte
<script lang="ts">
  let count: number = 0

  $: document.title = `${count}`
  $: doubled = count * 2
  $: isEven = count % 2 === 0
  const increment = () => {
    count += 1
  }
</script>

<!-- on:pointermove={(e) => count = e.clientX} -->
<button on:click={increment}>
  count is {count}
</button>

<p>{count} x 2 = {doubled}</p>
<p>
  {count} is

  {#if isEven}
  even
  {:else}
  odd
  {/if}
</p>

// spring2024/week9/react-client/src/components/Counter.tsx
import { useState, useMemo, useEffect } from 'react';

export default function Counter() {
  const [count, setCount] = useState(0);

  const doubledCount = useMemo(() => count * 2, [count]);
  const isEven = useMemo(() => count % 2 === 0, [count]);

  useEffect(() => {
    document.title = `${count}`;
  }, [count]);

  function increment() {
    setCount((count) => count + 1);
  }

  return (
    <div className="counter">
      <button onClick={increment}>
        count is {count}
      </button>
      <p>
        {count} x 2 = {doubledCount}
      </p>
      <p>
        {count} is {isEven ? 'even' : 'odd'}
      </p>
    </div>
  );
}
