// spring2024/week9/react-client/src/App.tsx
import './App.css'

import Counter from './components/Counter'
import Loops from './components/Loops'
import Card from './components/Card'

function App() {
  return (
    <>
      <div className="card">
        <Counter />
        <Loops />
        <Card title="Card title">
          <p>Card content</p>
          <a>link</a>
        </Card>
      </div>
    </>
  )
}

export default App

// spring2024/week9/svelte-client/src/App.svelte
<script lang="ts">
  import Counter from './lib/Counter.svelte'
  import Loops from './lib/Loops.svelte'
  import Fetch from './lib/Fetch.svelte'
  import Card from './lib/Card.svelte'
</script>

<main>
  <div>

  <div class="card">
    <Counter />
    <Loops />
    <Fetch />
    <Card title="Hello World">
      <p>Card content</p>
    </Card>
  </div>

</main>

<style>

</style>
